### ISSUE TITLE
类型不符合报错

### ISSUE THREAD

**Issue by sodasbyebye** [wstzj/MazeProblem#1]
char* reDirections(int direction) {
    switch (direction) { //下一步的方向,并存入节点
    case East:
        return "→";
    case North:
        return "↓";
    case West:
        return "←";
    case South:
        return "↑";
    case X:
        return "X";
    case O:
        return "O";
    default:
        return "E";
    }
}这里的符号不符合char*类型怎么解决呀

**Comment by wstzj** [comment]
可能存在编译环境的差异， 请尝试将 char* reDirections(int direction) 替换成 const char* reDirections(int direction)
